In [129]:
import gym
import numpy as np
weights = np.random.normal(0.0,0.1,4)

memory = []
seed=10
learning_rate = 0.05

In [115]:
def sigmoid(x):
    return 1/(1+np.exp(x))

def length(a):
    x = 0
    for element in a:
        x = x + element
    return x / len(a)

def execute(observation, weights):
    return int(round(sigmoid(length(observation*weights))))

def sort(memory):
    mean = np.sum(np.transpose(np.array(memory))[1]) / len(memory)
    i=0
    while i < len(memory):
        
        if memory[i][1] < mean:
            memory.pop(i)
            
        i += 1
    
    return memory
            



In [130]:
memory = []
env = gym.make('CartPole-v0')
for idx in range(5):
    for i_episode in range(seed):
        observation = env.reset()
        if idx == 0:
            weights = np.random.normal(0,0.2,4)
        else:
            weights = memory[i_episode][0] + np.random.normal(0,learning_rate,4)
        for t in range(100):
            env.render()
            print(observation)
            action = execute(observation,weights)
            print(action)
            observation, reward, done, info = env.step(action)
            if(done):
                print("Episode finished after {} timesteps".format(t+1))
                memory.append((weights, t))
                break
    sort(memory)
    seed = len(memory)

[2016-10-25 17:30:42,944] Making new env: CartPole-v0


[-0.04694787 -0.02767338 -0.01596882  0.0439813 ]
0
[-0.04750134 -0.22256275 -0.01508919  0.33158345]
0
[-0.0519526  -0.4174667  -0.00845752  0.61947005]
0
[-0.06030193 -0.61246951  0.00393188  0.90947732]
0
[-0.07255132 -0.80764446  0.02212143  1.20339344]
0
[-0.08870421 -1.00304531  0.04618929  1.50292618]
0
[-0.10876512 -1.19869647  0.07624782  1.80966474]
0
[-0.13273905 -1.39458115  0.11244111  2.1250332 ]
0
[-0.16063067 -1.59062719  0.15494178  2.45023333]
0
[-0.19244321 -1.78669028  0.20394644  2.7861757 ]
0
Episode finished after 10 timesteps
[-0.02285503 -0.0081924  -0.04641847  0.03617649]
0
[-0.02301888 -0.20261903 -0.04569494  0.31386016]
1
[-0.02707126 -0.00687693 -0.03941774  0.00712386]
0
[-0.0272088  -0.20141206 -0.03927526  0.28711407]
1
[-0.03123704 -0.00575265 -0.03353298 -0.01769266]
0
[-0.03135209 -0.20037805 -0.03388683  0.26422447]
1
[-0.03535965 -0.00478922 -0.02860234 -0.03895116]
0
[-0.03545543 -0.19948959 -0.02938136  0.24457199]
1
[-0.03944523 -0.00396057 -0.

In [132]:
np.argmax(np.transpose(memory)[1])

5

In [120]:
sort(memory)

[(array([-0.22299899,  0.02557583, -0.0714595 , -0.08524577]), 84),
 (array([ 0.56528189,  0.00710759, -0.08901745, -0.2601244 ]), 97)]

In [108]:
memory.remove(memory[0])

In [110]:
x = 0

In [111]:
x += 1

In [112]:
x

1